#cloud build
steps:
- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  args:
  - '-Dsonar.host.url=https://sonarcloud.io'
  - '-Dsonar.projectKey=$$SONAR_PROJECTKEY'
  - '-Dsonar.organization=$$SONAR_ORGKEY'
  - '-Dsonar.sources=src/productpage'
  secretEnv: ['SONAR_PROJECTKEY','SONAR_ORGKEY','SONAR_TOKEN']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/bookinfo/examples-bookinfo-productpage:$SHORT_SHA', '.']
  dir: 'src/productpage'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bookinfo/examples-bookinfo-productpage:$SHORT_SHA']
availableSecrets:
 secretManager:
   - versionName: projects/$PROJECT_ID/secrets/SONAR_PROJECTKEY/versions/latest
     env: SONAR_PROJECTKEY
   - versionName: projects/$PROJECT_ID/secrets/SONAR_ORGKEY/versions/latest
     env: SONAR_ORGKEY
   - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/latest
     env: SONAR_TOKEN