#cloud build
steps:
- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  args:
  - '-Dsonar.host.url=https://sonarcloud.io'
  - '-Dsonar.projectKey=$$SONARQ_PROJECTKEY'
  - '-Dsonar.organization=$_SONARQ_ORG'
  - '-Dsonar.sources=src/productpage'
  env:
  - 'SONAR_TOKEN=$_SONARQ_TOKEN'
  secretEnv: ['SONARQ_PROJECTKEY','SONARQ_ORG',SONARQ_TOKEN]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/bookinfo/examples-bookinfo-productpage:$SHORT_SHA', '.']
  dir: 'src/productpage'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bookinfo/examples-bookinfo-productpage:$SHORT_SHA']
availableSecrets:
 secretManager:
   - versionName: projects/$PROJECT_ID/secrets/SONAR_PROJECTKEY/versions/1
     env: 'SONARQ_PROJECTKEY'
   - versionName: projects/$PROJECT_ID/secrets/SONAR_ORG/versions/1
     env: 'SONARQ_ORG'
   - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/1
     env: 'SONARQ_TOKEN'